// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApp;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(FootballDbContext))]
    partial class FootballDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApp.Models.Club", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CleanSheets")
                        .HasColumnType("int");

                    b.Property<int>("Drawns")
                        .HasColumnType("int");

                    b.Property<int>("Goals")
                        .HasColumnType("int");

                    b.Property<int>("GoalsConceded")
                        .HasColumnType("int");

                    b.Property<int>("LeaguePoints")
                        .HasColumnType("int");

                    b.Property<int>("Losses")
                        .HasColumnType("int");

                    b.Property<int>("MatchesPlayed")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StadiumId")
                        .HasColumnType("int");

                    b.Property<int>("Wins")
                        .HasColumnType("int");

                    b.Property<int>("YearFounded")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StadiumId")
                        .IsUnique()
                        .HasFilter("[StadiumId] IS NOT NULL");

                    b.ToTable("Clubs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CleanSheets = 0,
                            Drawns = 0,
                            Goals = 0,
                            GoalsConceded = 0,
                            LeaguePoints = 0,
                            Losses = 0,
                            MatchesPlayed = 0,
                            Name = "Arsenal",
                            StadiumId = 1,
                            Wins = 0,
                            YearFounded = 1886
                        },
                        new
                        {
                            Id = 2,
                            CleanSheets = 0,
                            Drawns = 0,
                            Goals = 0,
                            GoalsConceded = 0,
                            LeaguePoints = 0,
                            Losses = 0,
                            MatchesPlayed = 0,
                            Name = "Aston Villa",
                            StadiumId = 2,
                            Wins = 0,
                            YearFounded = 1874
                        },
                        new
                        {
                            Id = 3,
                            CleanSheets = 0,
                            Drawns = 0,
                            Goals = 0,
                            GoalsConceded = 0,
                            LeaguePoints = 0,
                            Losses = 0,
                            MatchesPlayed = 0,
                            Name = "AFC Bournemouth",
                            StadiumId = 3,
                            Wins = 0,
                            YearFounded = 1899
                        },
                        new
                        {
                            Id = 4,
                            CleanSheets = 0,
                            Drawns = 0,
                            Goals = 0,
                            GoalsConceded = 0,
                            LeaguePoints = 0,
                            Losses = 0,
                            MatchesPlayed = 0,
                            Name = "Brentford",
                            StadiumId = 4,
                            Wins = 0,
                            YearFounded = 1889
                        },
                        new
                        {
                            Id = 5,
                            CleanSheets = 0,
                            Drawns = 0,
                            Goals = 0,
                            GoalsConceded = 0,
                            LeaguePoints = 0,
                            Losses = 0,
                            MatchesPlayed = 0,
                            Name = "Brighton and Hove Albion",
                            StadiumId = 5,
                            Wins = 0,
                            YearFounded = 1901
                        },
                        new
                        {
                            Id = 6,
                            CleanSheets = 0,
                            Drawns = 0,
                            Goals = 0,
                            GoalsConceded = 0,
                            LeaguePoints = 0,
                            Losses = 0,
                            MatchesPlayed = 0,
                            Name = "Burnley",
                            StadiumId = 6,
                            Wins = 0,
                            YearFounded = 1882
                        },
                        new
                        {
                            Id = 7,
                            CleanSheets = 0,
                            Drawns = 0,
                            Goals = 0,
                            GoalsConceded = 0,
                            LeaguePoints = 0,
                            Losses = 0,
                            MatchesPlayed = 0,
                            Name = "Chelsea",
                            StadiumId = 7,
                            Wins = 0,
                            YearFounded = 1905
                        },
                        new
                        {
                            Id = 8,
                            CleanSheets = 0,
                            Drawns = 0,
                            Goals = 0,
                            GoalsConceded = 0,
                            LeaguePoints = 0,
                            Losses = 0,
                            MatchesPlayed = 0,
                            Name = "Crystal Palace",
                            StadiumId = 8,
                            Wins = 0,
                            YearFounded = 1905
                        },
                        new
                        {
                            Id = 9,
                            CleanSheets = 0,
                            Drawns = 0,
                            Goals = 0,
                            GoalsConceded = 0,
                            LeaguePoints = 0,
                            Losses = 0,
                            MatchesPlayed = 0,
                            Name = "Everton",
                            StadiumId = 9,
                            Wins = 0,
                            YearFounded = 1878
                        },
                        new
                        {
                            Id = 10,
                            CleanSheets = 0,
                            Drawns = 0,
                            Goals = 0,
                            GoalsConceded = 0,
                            LeaguePoints = 0,
                            Losses = 0,
                            MatchesPlayed = 0,
                            Name = "Fulham",
                            StadiumId = 10,
                            Wins = 0,
                            YearFounded = 1879
                        },
                        new
                        {
                            Id = 11,
                            CleanSheets = 0,
                            Drawns = 0,
                            Goals = 0,
                            GoalsConceded = 0,
                            LeaguePoints = 0,
                            Losses = 0,
                            MatchesPlayed = 0,
                            Name = "Liverpool",
                            StadiumId = 11,
                            Wins = 0,
                            YearFounded = 1892
                        },
                        new
                        {
                            Id = 12,
                            CleanSheets = 0,
                            Drawns = 0,
                            Goals = 0,
                            GoalsConceded = 0,
                            LeaguePoints = 0,
                            Losses = 0,
                            MatchesPlayed = 0,
                            Name = "Luton Town",
                            StadiumId = 12,
                            Wins = 0,
                            YearFounded = 1885
                        },
                        new
                        {
                            Id = 13,
                            CleanSheets = 0,
                            Drawns = 0,
                            Goals = 0,
                            GoalsConceded = 0,
                            LeaguePoints = 0,
                            Losses = 0,
                            MatchesPlayed = 0,
                            Name = "Manchester City",
                            StadiumId = 13,
                            Wins = 0,
                            YearFounded = 1887
                        },
                        new
                        {
                            Id = 14,
                            CleanSheets = 0,
                            Drawns = 0,
                            Goals = 0,
                            GoalsConceded = 0,
                            LeaguePoints = 0,
                            Losses = 0,
                            MatchesPlayed = 0,
                            Name = "Manchester United",
                            StadiumId = 14,
                            Wins = 0,
                            YearFounded = 1878
                        },
                        new
                        {
                            Id = 15,
                            CleanSheets = 0,
                            Drawns = 0,
                            Goals = 0,
                            GoalsConceded = 0,
                            LeaguePoints = 0,
                            Losses = 0,
                            MatchesPlayed = 0,
                            Name = "Newcastle United",
                            StadiumId = 15,
                            Wins = 0,
                            YearFounded = 1892
                        },
                        new
                        {
                            Id = 16,
                            CleanSheets = 0,
                            Drawns = 0,
                            Goals = 0,
                            GoalsConceded = 0,
                            LeaguePoints = 0,
                            Losses = 0,
                            MatchesPlayed = 0,
                            Name = "Nottingham Forest",
                            StadiumId = 16,
                            Wins = 0,
                            YearFounded = 1865
                        },
                        new
                        {
                            Id = 17,
                            CleanSheets = 0,
                            Drawns = 0,
                            Goals = 0,
                            GoalsConceded = 0,
                            LeaguePoints = 0,
                            Losses = 0,
                            MatchesPlayed = 0,
                            Name = "Sheffield United",
                            StadiumId = 17,
                            Wins = 0,
                            YearFounded = 1889
                        },
                        new
                        {
                            Id = 18,
                            CleanSheets = 0,
                            Drawns = 0,
                            Goals = 0,
                            GoalsConceded = 0,
                            LeaguePoints = 0,
                            Losses = 0,
                            MatchesPlayed = 0,
                            Name = "Tottenham Hotspur",
                            StadiumId = 18,
                            Wins = 0,
                            YearFounded = 1882
                        },
                        new
                        {
                            Id = 19,
                            CleanSheets = 0,
                            Drawns = 0,
                            Goals = 0,
                            GoalsConceded = 0,
                            LeaguePoints = 0,
                            Losses = 0,
                            MatchesPlayed = 0,
                            Name = "West Ham United",
                            StadiumId = 19,
                            Wins = 0,
                            YearFounded = 1895
                        },
                        new
                        {
                            Id = 20,
                            CleanSheets = 0,
                            Drawns = 0,
                            Goals = 0,
                            GoalsConceded = 0,
                            LeaguePoints = 0,
                            Losses = 0,
                            MatchesPlayed = 0,
                            Name = "Wolverhampton Wanderers",
                            StadiumId = 20,
                            Wins = 0,
                            YearFounded = 1877
                        });
                });

            modelBuilder.Entity("WebApp.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClubId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<int>("KitNumber")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("WebApp.Models.Stadium", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YearBuilt")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Stadiums");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Adress = "Highbury House, 75 Drayton Park, London, N5 1BU",
                            Capacity = 60704,
                            Location = "London",
                            Name = "Emirates Stadium",
                            YearBuilt = 2006
                        },
                        new
                        {
                            Id = 2,
                            Adress = "Villa Park, Trinity Road, Birmingham, B6 6HE",
                            Capacity = 42530,
                            Location = "Birmingham",
                            Name = "Villa Park",
                            YearBuilt = 1897
                        },
                        new
                        {
                            Id = 3,
                            Adress = "Vitality Stadium, Dean Court, Bournemouth, BH7 7AF",
                            Capacity = 11307,
                            Location = "Bournemouth",
                            Name = "Vitality Stadium",
                            YearBuilt = 1910
                        },
                        new
                        {
                            Id = 4,
                            Adress = "Gtech Community Stadium, Lionel Road South, Brentford, TW8 0RU",
                            Capacity = 17250,
                            Location = "Brentford",
                            Name = "Gtech Community Stadium",
                            YearBuilt = 2000
                        },
                        new
                        {
                            Id = 5,
                            Adress = "American Express Community Stadium, Village Way, Brighton, BN1 9BL",
                            Capacity = 31876,
                            Location = "Falmer",
                            Name = "American Express Stadium",
                            YearBuilt = 2011
                        },
                        new
                        {
                            Id = 6,
                            Adress = "Turf Moor, Harry Potts Way, Burnley, Lancashire, BB10 4BX",
                            Capacity = 21944,
                            Location = "Burnley",
                            Name = "Turf Moor",
                            YearBuilt = 1883
                        },
                        new
                        {
                            Id = 7,
                            Adress = "Stamford Bridge, Fulham Road, London, SW6 1HS",
                            Capacity = 40343,
                            Location = "London",
                            Name = "Stamford Bridge",
                            YearBuilt = 1877
                        },
                        new
                        {
                            Id = 8,
                            Adress = "Selhurst Park Stadium, Holmesdale Road, London, SE25 6PU",
                            Capacity = 25486,
                            Location = "London",
                            Name = "Selhurst Park",
                            YearBuilt = 1924
                        },
                        new
                        {
                            Id = 9,
                            Adress = "Goodison Park, Goodison Road, Liverpool, L4 4EL",
                            Capacity = 39414,
                            Location = "Liverpool",
                            Name = "Goodison Park",
                            YearBuilt = 1892
                        },
                        new
                        {
                            Id = 10,
                            Adress = "Stevenage Road, London, SW6 6HH",
                            Capacity = 24500,
                            Location = "London",
                            Name = "Craven Cottage",
                            YearBuilt = 1896
                        },
                        new
                        {
                            Id = 11,
                            Adress = "Anfield, Anfield Road, Liverpool, L4 0TH",
                            Capacity = 61276,
                            Location = "Liverpool",
                            Name = "Anfield",
                            YearBuilt = 1884
                        },
                        new
                        {
                            Id = 12,
                            Adress = "Kenilworth Road Stadium, 1 Maple Road, Luton, LU4 8AW",
                            Capacity = 10265,
                            Location = "Luton",
                            Name = "Kenilworth Road",
                            YearBuilt = 1905
                        },
                        new
                        {
                            Id = 13,
                            Adress = "Etihad Stadium, Etihad Campus, Manchester, M11 3FF",
                            Capacity = 53400,
                            Location = "Manchester",
                            Name = "Etihad Stadium,",
                            YearBuilt = 2002
                        },
                        new
                        {
                            Id = 14,
                            Adress = "Sir Matt Busby Way, Old Trafford, Manchester, M16 0RA",
                            Capacity = 74310,
                            Location = "Manchester",
                            Name = "Old Trafford",
                            YearBuilt = 1909
                        },
                        new
                        {
                            Id = 15,
                            Adress = "St. James' Park, Newcastle Upon Tyne, NE1 4ST",
                            Capacity = 52305,
                            Location = "Newcastle",
                            Name = "St. James' Park",
                            YearBuilt = 1892
                        },
                        new
                        {
                            Id = 16,
                            Adress = "Nottingham Forest Football Club, The City Ground, Pavilion Road, West Bridgford, Nottingham, NG2 5FJ",
                            Capacity = 30404,
                            Location = "Nottingham",
                            Name = "The City Ground",
                            YearBuilt = 1898
                        },
                        new
                        {
                            Id = 17,
                            Adress = "Bramall Lane, Sheffield, South Yorkshire, S2 4SU",
                            Capacity = 32050,
                            Location = "Sheffield",
                            Name = "Bramall Lane",
                            YearBuilt = 1855
                        },
                        new
                        {
                            Id = 18,
                            Adress = "Lilywhite House, 782 High Road, Tottenham, London, N17 0BX",
                            Capacity = 62850,
                            Location = "London",
                            Name = "Tottenham Hotspur Stadium",
                            YearBuilt = 2019
                        },
                        new
                        {
                            Id = 19,
                            Adress = "London Stadium, Queen Elizabeth Olympic Park, London, E20 2ST",
                            Capacity = 62500,
                            Location = "London",
                            Name = "London Stadium",
                            YearBuilt = 2011
                        },
                        new
                        {
                            Id = 20,
                            Adress = "Molineux Stadium, Waterloo Rd, Wolverhampton, WV1 4QR",
                            Capacity = 31750,
                            Location = "Wolverhampton",
                            Name = "Molineux Stadium",
                            YearBuilt = 1889
                        });
                });

            modelBuilder.Entity("WebApp.Models.Club", b =>
                {
                    b.HasOne("WebApp.Models.Stadium", "Stadium")
                        .WithOne("Club")
                        .HasForeignKey("WebApp.Models.Club", "StadiumId");

                    b.Navigation("Stadium");
                });

            modelBuilder.Entity("WebApp.Models.Player", b =>
                {
                    b.HasOne("WebApp.Models.Club", "Club")
                        .WithMany("Players")
                        .HasForeignKey("ClubId");

                    b.Navigation("Club");
                });

            modelBuilder.Entity("WebApp.Models.Club", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("WebApp.Models.Stadium", b =>
                {
                    b.Navigation("Club");
                });
#pragma warning restore 612, 618
        }
    }
}
