// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApp;

#nullable disable

namespace WebApp.Migrations
{
    [DbContext(typeof(AppDb))]
    [Migration("20240412215145_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApp.Models.Club", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CleanSheets")
                        .HasColumnType("int");

                    b.Property<int>("Drawns")
                        .HasColumnType("int");

                    b.Property<int>("Goals")
                        .HasColumnType("int");

                    b.Property<int>("GoalsConceded")
                        .HasColumnType("int");

                    b.Property<int>("LeaguePoints")
                        .HasColumnType("int");

                    b.Property<int>("Losses")
                        .HasColumnType("int");

                    b.Property<int>("MatchesPlayed")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Wins")
                        .HasColumnType("int");

                    b.Property<int>("YearFounded")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Clubs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CleanSheets = 0,
                            Drawns = 0,
                            Goals = 0,
                            GoalsConceded = 0,
                            LeaguePoints = 0,
                            Losses = 0,
                            MatchesPlayed = 0,
                            Name = "Arsenal",
                            Wins = 0,
                            YearFounded = 1886
                        },
                        new
                        {
                            Id = 2,
                            CleanSheets = 0,
                            Drawns = 0,
                            Goals = 0,
                            GoalsConceded = 0,
                            LeaguePoints = 0,
                            Losses = 0,
                            MatchesPlayed = 0,
                            Name = "Aston Villa",
                            Wins = 0,
                            YearFounded = 1874
                        },
                        new
                        {
                            Id = 3,
                            CleanSheets = 0,
                            Drawns = 0,
                            Goals = 0,
                            GoalsConceded = 0,
                            LeaguePoints = 0,
                            Losses = 0,
                            MatchesPlayed = 0,
                            Name = "AFC Bournemouth",
                            Wins = 0,
                            YearFounded = 1899
                        },
                        new
                        {
                            Id = 4,
                            CleanSheets = 0,
                            Drawns = 0,
                            Goals = 0,
                            GoalsConceded = 0,
                            LeaguePoints = 0,
                            Losses = 0,
                            MatchesPlayed = 0,
                            Name = "Brentford",
                            Wins = 0,
                            YearFounded = 1889
                        },
                        new
                        {
                            Id = 5,
                            CleanSheets = 0,
                            Drawns = 0,
                            Goals = 0,
                            GoalsConceded = 0,
                            LeaguePoints = 0,
                            Losses = 0,
                            MatchesPlayed = 0,
                            Name = "Brighton and Hove Albion",
                            Wins = 0,
                            YearFounded = 1901
                        },
                        new
                        {
                            Id = 6,
                            CleanSheets = 0,
                            Drawns = 0,
                            Goals = 0,
                            GoalsConceded = 0,
                            LeaguePoints = 0,
                            Losses = 0,
                            MatchesPlayed = 0,
                            Name = "Burnley",
                            Wins = 0,
                            YearFounded = 1882
                        },
                        new
                        {
                            Id = 7,
                            CleanSheets = 0,
                            Drawns = 0,
                            Goals = 0,
                            GoalsConceded = 0,
                            LeaguePoints = 0,
                            Losses = 0,
                            MatchesPlayed = 0,
                            Name = "Chelsea",
                            Wins = 0,
                            YearFounded = 1905
                        },
                        new
                        {
                            Id = 8,
                            CleanSheets = 0,
                            Drawns = 0,
                            Goals = 0,
                            GoalsConceded = 0,
                            LeaguePoints = 0,
                            Losses = 0,
                            MatchesPlayed = 0,
                            Name = "Crystal Palace",
                            Wins = 0,
                            YearFounded = 1905
                        },
                        new
                        {
                            Id = 9,
                            CleanSheets = 0,
                            Drawns = 0,
                            Goals = 0,
                            GoalsConceded = 0,
                            LeaguePoints = 0,
                            Losses = 0,
                            MatchesPlayed = 0,
                            Name = "Everton",
                            Wins = 0,
                            YearFounded = 1878
                        },
                        new
                        {
                            Id = 10,
                            CleanSheets = 0,
                            Drawns = 0,
                            Goals = 0,
                            GoalsConceded = 0,
                            LeaguePoints = 0,
                            Losses = 0,
                            MatchesPlayed = 0,
                            Name = "Fulham",
                            Wins = 0,
                            YearFounded = 1879
                        },
                        new
                        {
                            Id = 11,
                            CleanSheets = 0,
                            Drawns = 0,
                            Goals = 0,
                            GoalsConceded = 0,
                            LeaguePoints = 0,
                            Losses = 0,
                            MatchesPlayed = 0,
                            Name = "Liverpool",
                            Wins = 0,
                            YearFounded = 1892
                        },
                        new
                        {
                            Id = 12,
                            CleanSheets = 0,
                            Drawns = 0,
                            Goals = 0,
                            GoalsConceded = 0,
                            LeaguePoints = 0,
                            Losses = 0,
                            MatchesPlayed = 0,
                            Name = "Luton Town",
                            Wins = 0,
                            YearFounded = 1885
                        },
                        new
                        {
                            Id = 13,
                            CleanSheets = 0,
                            Drawns = 0,
                            Goals = 0,
                            GoalsConceded = 0,
                            LeaguePoints = 0,
                            Losses = 0,
                            MatchesPlayed = 0,
                            Name = "Manchester City",
                            Wins = 0,
                            YearFounded = 1887
                        },
                        new
                        {
                            Id = 14,
                            CleanSheets = 0,
                            Drawns = 0,
                            Goals = 0,
                            GoalsConceded = 0,
                            LeaguePoints = 0,
                            Losses = 0,
                            MatchesPlayed = 0,
                            Name = "Manchester United",
                            Wins = 0,
                            YearFounded = 1878
                        },
                        new
                        {
                            Id = 15,
                            CleanSheets = 0,
                            Drawns = 0,
                            Goals = 0,
                            GoalsConceded = 0,
                            LeaguePoints = 0,
                            Losses = 0,
                            MatchesPlayed = 0,
                            Name = "Newcastle United",
                            Wins = 0,
                            YearFounded = 1892
                        },
                        new
                        {
                            Id = 16,
                            CleanSheets = 0,
                            Drawns = 0,
                            Goals = 0,
                            GoalsConceded = 0,
                            LeaguePoints = 0,
                            Losses = 0,
                            MatchesPlayed = 0,
                            Name = "Nottingham Forest",
                            Wins = 0,
                            YearFounded = 1865
                        },
                        new
                        {
                            Id = 17,
                            CleanSheets = 0,
                            Drawns = 0,
                            Goals = 0,
                            GoalsConceded = 0,
                            LeaguePoints = 0,
                            Losses = 0,
                            MatchesPlayed = 0,
                            Name = "Sheffield United",
                            Wins = 0,
                            YearFounded = 1889
                        },
                        new
                        {
                            Id = 18,
                            CleanSheets = 0,
                            Drawns = 0,
                            Goals = 0,
                            GoalsConceded = 0,
                            LeaguePoints = 0,
                            Losses = 0,
                            MatchesPlayed = 0,
                            Name = "Tottenham Hotspur",
                            Wins = 0,
                            YearFounded = 1882
                        },
                        new
                        {
                            Id = 19,
                            CleanSheets = 0,
                            Drawns = 0,
                            Goals = 0,
                            GoalsConceded = 0,
                            LeaguePoints = 0,
                            Losses = 0,
                            MatchesPlayed = 0,
                            Name = "West Ham United",
                            Wins = 0,
                            YearFounded = 1895
                        },
                        new
                        {
                            Id = 20,
                            CleanSheets = 0,
                            Drawns = 0,
                            Goals = 0,
                            GoalsConceded = 0,
                            LeaguePoints = 0,
                            Losses = 0,
                            MatchesPlayed = 0,
                            Name = "Wolverhampton Wanderers",
                            Wins = 0,
                            YearFounded = 1877
                        });
                });

            modelBuilder.Entity("WebApp.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClubId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<int>("KitNumber")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("WebApp.Models.Player", b =>
                {
                    b.HasOne("WebApp.Models.Club", "Club")
                        .WithMany("Players")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");
                });

            modelBuilder.Entity("WebApp.Models.Club", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
